config = {'datapath':'/mnt/lustre/liuxinglong/data/ISBI/isbi_preprocess/rawdata_multiple/',
          'preprocess_result_path':'./prep_result_multiple/',
          'outputfile':'./prediction_test_multiple.csv',
          'bbox_path': './bbox_result',
          'detector_model':'net_detector',
         'detector_param':'./model/detector.ckpt',
         'classifier_model':'net_classifier',
         'classifier_param':'./model/classifier.ckpt',
         'n_gpu':8,
         'n_worker_preprocessing':4,
         'use_exsiting_preprocessing':True,
         'skip_preprocessing':True,
         'skip_detect':True,
         'feature_path': './features_multiple/'}
