config = {'datapath':'/mnt/lustre/liuxinglong/data/YiZhong/rawdata/',
          'preprocess_result_path':'./prep_result_yizhong/',
          'outputfile':'./prediction_test_yizhong.csv',
          'bbox_path': './bbox_result_yizhong',
          'detector_model':'net_detector',
         'detector_param':'./model/detector.ckpt',
         'classifier_model':'net_classifier',
         'classifier_param':'./model/classifier.ckpt',
         'n_gpu':8,
         'n_worker_preprocessing':4,
         'use_exsiting_preprocessing':True,
         'skip_preprocessing':True,
         'skip_detect':False,
         'feature_path': './features_yizhong/'}
